### ISSUE TITLE
SI issues

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/DIO_MCX#2]
does it make sense to tune lengths of traces between channels?
For 74LVT162245MTD the DS says
![obraz](https://user-images.githubusercontent.com/4325054/65277852-18f07800-db2b-11e9-9467-c2d4b6a989f6.png)

For
SN65MLVD040RGZT it says
![obraz](https://user-images.githubusercontent.com/4325054/65277829-0c6c1f80-db2b-11e9-8b92-981a34ebbcc9.png)

At the moment trace length difference is roughly 60mm,  so IMHO it does not make much sense.

**Comment by jordens** [comment]
For this nodule not necessary IMO
