### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/DIO_MCX#3]
`P12V0 current is up to 600mA with all 8 channels shorted to GND` assume this was copied from the other DIO cards. Needs to be updated for 16 ch board.

**Comment by hartytp** [comment]
NB if you short all channels then you'll exceed the current rating of the NCP3170ADR2G and the power will cut out. Fine IMHO but worth noting.

Also, can the inductors, traces etc take the max current the 3V3 SMPS can supply or will they burn out?

**Comment by gkasprow** [comment]
Well, I can use 6A power supply, but I would have to add thermal protection :) We have an entire plane for 3V distribution

**Comment by gkasprow** [comment]
added annotation to schematics
