### ISSUE TITLE
jitter

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/DIO_MCX#4]
what's your target jitter for this design? How much have you thought about the jitter on the buffers?

**Comment by gkasprow** [comment]
I didn't think about it intensively. We are anyway limited by LVCMOS buffers which do not have it specified.
To limit inter-channel influence, which causes additional jitter, I used only half of the channels to limit the ground bouncing.
I can also connect inputs and outputs to GND or VCC to further lower the supply impedance. 
LVDS interface IC has 290ps jitter when treated with PRBS signal on all channels. With a single clock signal, the jitter is just 2ps. 
If we want a very low jitter module, I would have to replace the LVDS buffers with single-channel ones, the same with LVTTL drivers.

**Comment by gkasprow** [comment]
nothing to do here, closing
